# Generated by Django 5.2.5 on 2026-04-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.JSONField(default=list, help_text='JSON representation of the rich text editor content.'),
        ),
    ]
