# Generated by Django 5.2.5 on 2026-04-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.JSONField(blank=True, default=list, help_text='JSON representation of the rich text editor content.', null=True),
        ),
    ]
